print("Protocol Parameters: Number of Basis Choices: 2 (Rectilinear or Diagonal)")
    # print("Alice's Bits: ", alice_bits)
    # print("Bob's Basis: ", bob_basis)
    # print("Bob's Bits: ", bob_bits)
    # print("Sifted Key: ", sifted_key)
    # print("Bit Error Rate (BER): ", ber)
    # print("Eve's Success Rate Estimate: ", eve_success_rate_estimate)
    # print("Noise Level: ", noise_level)
    # print("Eve's Attack Type:", attack_type)